const FoodItems = [
    { id: 1, name: 'Beef', calories: 250 },
    { id: 2, name: 'Chicken', calories: 239 },
    { id: 3, name: 'Lamb', calories: 294 },
    { id: 4, name: 'Lobster', calories: 98 },
    { id: 5, name: 'Salmon', calories: 208 },
    { id: 6, name: 'Tuna', calories: 132 },
    { id: 7, name: 'Turkey', calories: 189 },
    { id: 8, name: 'Cod', calories: 82 },
    { id: 9, name: 'Shrimp', calories: 99 },
    { id: 10, name: 'Crab', calories: 87 },
    { id: 11, name: 'Egg', calories: 155 },
    { id: 12, name: 'Tofu', calories: 76 },
    { id: 13, name: 'Raddish', calories: 16 },
    { id: 14, name: 'Lentils', calories: 116 },
    { id: 15, name: 'Black Beans', calories: 132 },
    { id: 16, name: 'Chickpeas', calories: 164 },
    { id: 17, name: 'Quinoa', calories: 120 },
    { id: 18, name: 'Brown Rice', calories: 123 },
    { id: 19, name: 'White Rice', calories: 130 },
    { id: 20, name: 'Oats', calories: 389 },
    { id: 21, name: 'Almonds', calories: 579 },
    { id: 22, name: 'Walnuts', calories: 654 },
    { id: 23, name: 'Cashews', calories: 553 },
    { id: 24, name: 'Pistachios', calories: 562 },
    { id: 25, name: 'Peanuts', calories: 567 },
    { id: 26, name: 'Banana', calories: 89 },
    { id: 27, name: 'Apple', calories: 52 },
    { id: 28, name: 'Orange', calories: 47 },
    { id: 29, name: 'Grapes', calories: 69 },
    { id: 30, name: 'Strawberries', calories: 32 },
    { id: 31, name: 'Blueberries', calories: 57 },
    { id: 32, name: 'Raspberries', calories: 52 },
    { id: 33, name: 'Pineapple', calories: 50 },
    { id: 34, name: 'Mango', calories: 60 },
    { id: 35, name: 'Avocado', calories: 160 },
    { id: 36, name: 'Tomato', calories: 18 },
    { id: 37, name: 'Cucumber', calories: 16 },
    { id: 38, name: 'Carrot', calories: 41 },
    { id: 39, name: 'Broccoli', calories: 34 },
    { id: 40, name: 'Spinach', calories: 23 },
    { id: 41, name: 'Kale', calories: 49 },
    { id: 42, name: 'Cauliflower', calories: 25 },
    { id: 43, name: 'Zucchini', calories: 17 },
    { id: 44, name: 'Eggplant', calories: 25 },
    { id: 45, name: 'Bell Pepper', calories: 31 },
    { id: 46, name: 'Sweet Potato', calories: 86 },
    { id: 47, name: 'Potato', calories: 77 },
    { id: 48, name: 'Onion', calories: 40 },
    { id: 49, name: 'Garlic', calories: 149 },
    { id: 50, name: 'Pumpkin', calories: 26 },
    { id: 51, name: 'Peas', calories: 81 },
    { id: 52, name: 'Corn', calories: 86 },
    { id: 53, name: 'Cabbage', calories: 25 },
    { id: 54, name: 'Brussels Sprouts', calories: 43 },
    { id: 55, name: 'Asparagus', calories: 20 },
    { id: 56, name: 'Lettuce', calories: 15 },
    { id: 57, name: 'Celery', calories: 16 },
    { id: 58, name: 'Mushrooms', calories: 22 },
    { id: 59, name: 'Coconut', calories: 354 },
    { id: 60, name: 'Chia Seeds', calories: 486 },
    { id: 61, name: 'Flaxseeds', calories: 534 },
    { id: 62, name: 'Sunflower Seeds', calories: 584 },
    { id: 63, name: 'Hazelnuts', calories: 628 },
    { id: 64, name: 'Macadamia Nuts', calories: 718 },
    { id: 65, name: 'Brazil Nuts', calories: 659 },
    { id: 66, name: 'Pomegranate', calories: 83 },
    { id: 67, name: 'Kiwi', calories: 61 },
    { id: 68, name: 'Papaya', calories: 43 },
    { id: 69, name: 'Plum', calories: 46 },
    { id: 70, name: 'Apricot', calories: 48 },
    { id: 71, name: 'Pear', calories: 57 },
    { id: 72, name: 'Watermelon', calories: 30 },
    { id: 73, name: 'Cantaloupe', calories: 34 },
    { id: 74, name: 'Honeydew Melon', calories: 36 },
    { id: 75, name: 'Fig', calories: 74 },
    { id: 76, name: 'Dates', calories: 282 },
    { id: 77, name: 'Raisins', calories: 299 },
    { id: 78, name: 'Prunes', calories: 240 },
    { id: 79, name: 'Olives', calories: 115 },
    { id: 80, name: 'Butter', calories: 717 },
    { id: 81, name: 'Cheddar Cheese', calories: 402 },
    { id: 82, name: 'Mozzarella', calories: 280 },
    { id: 83, name: 'Greek Yogurt', calories: 59 },
    { id: 84, name: 'Milk', calories: 42 },
    { id: 85, name: 'Cottage Cheese', calories: 98 },
    { id: 86, name: 'Ice Cream', calories: 207 },
    { id: 87, name: 'Bread', calories: 265 },
    { id: 88, name: 'Bagel', calories: 250 },
    { id: 89, name: 'Pasta', calories: 131 },
    { id: 90, name: 'Pizza', calories: 266 },
    { id: 91, name: 'Croissant', calories: 406 },
    { id: 92, name: 'Donut', calories: 452 },
    { id: 93, name: 'Chocolate', calories: 546 },
    { id: 94, name: 'Popcorn', calories: 375 },
    { id: 95, name: 'Potato Chips', calories: 536 },
    { id: 96, name: 'Pretzels', calories: 380 },
    { id: 97, name: 'Granola', calories: 471 },
    { id: 98, name: 'Honey', calories: 304 },
    { id: 99, name: 'Maple Syrup', calories: 260 },
    { id: 100, name: 'Peanut Butter', calories: 588 }
  ];

  module.exports = FoodItems;